// Generated by CoffeeScript 1.8.0
(function() {
  var krb5;

  krb5 = require('./build/Release/krb5');

  module.exports = function(obj, next) {
    var k, realm, toto, user, _ref;
    if (typeof obj !== 'object') {
      return next('Params: Not an object');
    }
    if (obj.user_principal == null) {
      return next('Params: Please set user_principal property');
    }
    if (!obj.user_principal.match(/[A-Za-z0-9_\-\/]*@[A-Za-z0-9_\-\.]*/)) {
      return next('Params: user_principal is unvalid, please use ID@REALM');
    }
    if (obj.service_principal == null) {
      return next('Params: please set service_principal property');
    }
    if (!obj.service_principal.match(/[A-Za-z0-9_\-\/]*@[A-Za-z0-9_\-\.]*/)) {
      return next('Params: service_principal is unvalid, please use ID@REALM');
    }
    _ref = obj.user_principal.split('@'), user = _ref[0], realm = _ref[1];
    k = new krb5.Krb5(user, realm);
    if (obj.user_password) {
      k.getCredentialsByPasswordSync(obj.user_password);
    } else {
      k.getCredentialsByKeytabSync(obj.user_keytab);
    }
    toto = k.generateSpnegoTokenSync(obj.service_principal);
    return next(k.err, k.token);
  };

}).call(this);
