version: '3'
services:
  kerberos:
    build: ./kdc
    image: krb5_kdc
    volumes:
      - /dev/urandom:/dev/random
      - /tmp/krb5_test:/tmp/krb5_test
    hostname: kdc.krb.local
    ports:
      - 8088:88
      - 8749:749
    environment:
      BOOTSTRAP: 1
  rest:
    build: ./rest
    image: krb5_rest
    hostname: rest.krb.local
    depends_on:
      - kerberos
    links:
      - "kerberos:kdc.krb.local"
    ports:
      - 8080:8080
    volumes:
      - ../src/server.py:/node-krb5/src/server.py
      - /tmp/krb5_test:/tmp/krb5_test
  archlinux:
    build: 
      context: ../
      dockerfile: docker/archlinux/Dockerfile
    image: krb5_archlinux
    depends_on:
      - kerberos
      - rest
    links:
      - "kerberos:kdc.krb.local"
      - "rest:rest.krb.local"
    volumes:
      - /tmp/krb5_test:/tmp/krb5_test
  centos7:
    build: 
      context: ../
      dockerfile: docker/centos7/Dockerfile
    image: krb5_centos7
    depends_on:
      - kerberos
      - rest
    links:
      - "kerberos:kdc.krb.local"
      - "rest:rest.krb.local"
    volumes:
      - /tmp/krb5_test:/tmp/krb5_test
  ubuntu:
    build: 
      context: ../
      dockerfile: docker/ubuntu/Dockerfile
    image: krb5_ubuntu
    depends_on:
      - kerberos
      - rest
    links:
      - "kerberos:kdc.krb.local"
      - "rest:rest.krb.local"
    volumes:
      - /tmp/krb5_test:/tmp/krb5_test
  ubuntu-vendored:
    build: 
      context: ../
      dockerfile: docker/ubuntu-vendored/Dockerfile
    image: krb5_ubuntu_vendored
    depends_on:
      - kerberos
      - rest
    links:
      - "kerberos:kdc.krb.local"
      - "rest:rest.krb.local"
    volumes:
      - /tmp/krb5_test:/tmp/krb5_test
