/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KdestroyParameters {
  ccname?: string | undefined | null
}
export interface KinitParameters {
  principal: string
  password?: string | undefined | null
  keytab?: string | undefined | null
  realm?: string | undefined | null
  ccname?: string | undefined | null
}
export interface GenerateSpnegoTokenParameters {
  service_principal?: string | undefined | null
  service_fqdn?: string | undefined | null
  hostbased_service?: string | undefined | null
  ccname?: string | undefined | null
}
export function kinit(input: KinitParameters): Promise<string>
export function kdestroy(input: KdestroyParameters): Promise<void>
export function spnego(input: GenerateSpnegoTokenParameters): Promise<string>
